apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: http
      port: 8080        # service port
      targetPort: 8080  # container port
      nodePort: 30080   # NodePort on the node

